// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQNS_4FqPZwGcjwZxJ9WdLh5XhazT9aCk',
    appId: '1:288788313210:web:2ab93d0a89f91b4555b7c3',
    messagingSenderId: '288788313210',
    projectId: 'gratitudejournal-8e7b7',
    authDomain: 'gratitudejournal-8e7b7.firebaseapp.com',
    storageBucket: 'gratitudejournal-8e7b7.firebasestorage.app',
    measurementId: 'G-DXVEFN8V91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLHcLioQnCD_Pxa26aHKSIY5vt2ID_tR4',
    appId: '1:428332079370:android:fad00433cc8a312803c2f3',
    messagingSenderId: '428332079370',
    projectId: 'gratitudejournal-b576d',
    storageBucket: 'gratitudejournal-b576d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHyQSgmeoJmLDb283VDfvFISA6PsYnYmI',
    appId: '1:288788313210:ios:c64b12491896279755b7c3',
    messagingSenderId: '288788313210',
    projectId: 'gratitudejournal-8e7b7',
    storageBucket: 'gratitudejournal-8e7b7.firebasestorage.app',
    iosBundleId: 'com.example.gratitudeJournal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHyQSgmeoJmLDb283VDfvFISA6PsYnYmI',
    appId: '1:288788313210:ios:c64b12491896279755b7c3',
    messagingSenderId: '288788313210',
    projectId: 'gratitudejournal-8e7b7',
    storageBucket: 'gratitudejournal-8e7b7.firebasestorage.app',
    iosBundleId: 'com.example.gratitudeJournal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQNS_4FqPZwGcjwZxJ9WdLh5XhazT9aCk',
    appId: '1:288788313210:web:2fba094e406369ea55b7c3',
    messagingSenderId: '288788313210',
    projectId: 'gratitudejournal-8e7b7',
    authDomain: 'gratitudejournal-8e7b7.firebaseapp.com',
    storageBucket: 'gratitudejournal-8e7b7.firebasestorage.app',
    measurementId: 'G-WF5P5ZKDYY',
  );

}